Unit test fixes; log file path corrections; bumped pipeline and branding versions.
xenserver/xenadmin pull request #2838
Opened 2021-07-28 14:55 UTC by kc284

2021-07-29 09:09 UTC, CitrixChris requested changes

2021-07-29 10:42 UTC, kc284 commented on Jenkinsfile
> +@Library(['PacmanSharedLibrary', "xencenter-pipeline@v4.1"])
Yes. They refer to different repos. Currently the latest tags both in branding and pipeline are 4.0, but the pipeline will be 4.1 after the PR with the test correction is merged.

2021-07-29 11:30 UTC, AaronRobson approved these changes

2021-07-29 11:38 UTC, kc284 commented
Pushed a correction so the test can be run locally without branding applied.

2021-07-30 05:13 UTC, MihaelaStoica approved these changes

2021-07-30 09:48 UTC, CitrixChris approved these changes

2021-07-30 16:17 UTC, merged