CA-350411: Add conditional page control refresh in Import Wizard
xenserver/xenadmin pull request #2842
Opened 2021-08-02 13:28 UTC by danilo-delbusso

Page controls are now forcefully refreshed only when necessary.

2021-08-09 12:49 UTC, CitrixChris submitted a review, later dismissed

2021-09-06 12:52 UTC, kc284 requested changes
We can also add checks for the page types ImportSourcePage and GlobalSelectHost.

2021-09-06 12:52 UTC, kc284 commented on XenAdmin/Wizards/ImportWizard/ImportWizard.cs
> +				if (m_pageStorage.SelectedOvfEnvelope != m_envelopeFromVhd
An easier way to do this is assign the newly created envelope to a local variable and compare this with `m_envelopeFromVhd` before assigning to the latter:
```
var newEnv = OVF.Create(...);
if (newEnv != m_envelopeFromVhd) {...}
m_envelopeFromVhd = newEnv;
```

2021-09-06 12:52 UTC, kc284 commented on XenAdmin/Wizards/ImportWizard/ImportWizard.cs
> +					|| m_pageStorage.VmMappings != m_vmMappings
The m_vmMappings are set further down; at this point they have not changed yet, so the comparison with m_pageStorage.VmMappings is always true. However, I suggest using local variables for comparing the connection and mappings (like with the OvfEnvelope in the previous comment).

Also,  the removal/addition of the boot options page is not needed if the import type or connection have not changed.

2021-09-20 13:23 UTC, AaronRobson submitted a review, later dismissed

2021-11-24 12:21 UTC, kc284 commented
This one proved trickier than anticipated and there was also an additional bug whereby the Boot options selected by the user were not set correctly when one imported VM from image. I have submitted some corrections here https://github.com/danilo-delbusso/xenadmin/pull/9. The whole thing will need re-review once merged and a lot of testing because there is a risk of the changes introducing regressions.

2021-11-24 12:22 UTC, kc284 requested changes
Setting it status to "changes requested" until we review and merge https://github.com/danilo-delbusso/xenadmin/pull/9

2021-11-24 12:36 UTC, danilo-delbusso commented on XenAdmin/Wizards/ImportWizard/NetworkPickerPage.cs
> +		internal IXenConnection MSelectedConnection { get; set; }
Thanks! I was wondering what that was 😂

2021-12-02 12:06 UTC, AaronRobson approved these changes

2021-12-02 13:54 UTC, CitrixChris approved these changes

2021-12-02 21:01 UTC, merged