Replaced travis build with github actions. Updated maintainers.
xenserver/xenadmin pull request #2855
Opened 2021-08-11 09:21 UTC by kc284

2021-08-11 13:37 UTC, danilo-delbusso requested changes

2021-08-11 13:37 UTC, danilo-delbusso commented on README.md
> -[![Build Status](https://travis-ci.org/xenserver/xenadmin.svg?branch=master)](https://travis-ci.org/xenserver/xenadmin)
GitHub also allows for action statuses to [be shown in the README.md](
https://docs.github.com/en/actions/managing-workflow-runs/adding-a-workflow-status-badge). I would switch to that to keep the label if possible, which some might find useful.

2021-08-12 08:04 UTC, danilo-delbusso approved these changes

2021-08-16 09:17 UTC, CitrixChris approved these changes

2021-08-16 10:01 UTC, merged