CP-34231: Replace negative language with `coordinator`
xenserver/xenadmin pull request #2858
Opened 2021-08-16 13:55 UTC by danilo-delbusso

Renamed negative language from .resx strings.

2021-08-17 14:37 UTC, kc284 requested changes

2021-08-17 14:37 UTC, kc284 commented on XenAdmin/Dialogs/NewPoolDialog.resx
> +    <value>&amp;Coordinator:</value>
Now this has the same hotkey as buttonCreate `&amp;Create Pool`. The hotkeys on the dialog should be unique, or the user will have trouble focusing on the control when clicking Alt+C. Just move the ampersand to a letter not already in use elsewhere in NewPoolDialog.resx.

2021-08-17 22:51 UTC, kc284 approved these changes

2021-08-19 09:04 UTC, danilo-delbusso commented
Closed as all changes have been moved to https://github.com/xenserver/xenadmin/pull/2860

2021-08-19 09:04 UTC, closed without merging