Merge feature/REQ-403 into master
xenserver/xenadmin pull request #2867
Opened 2021-09-01 17:20 UTC by kc284

2021-09-06 14:10 UTC, danilo-delbusso requested changes

2021-09-06 14:29 UTC, kc284 commented on XenModel/FriendlyNames.resx
> +    <value>Certificate verification is enabled on the pool, but overriden on server '{0}'.</value>
I've put the fix in https://github.com/xenserver/xenadmin/pull/2868. Once the latter is merged, this one will be updated automatically.

2021-09-06 15:43 UTC, danilo-delbusso approved these changes

2021-09-07 09:59 UTC, MihaelaStoica approved these changes

2021-09-07 15:55 UTC, merged