CA-359124 & CA-360426: Add snapshot VIFs to mapping during cross pool migration & fix VIF mapping in cross pool migration
xenserver/xenadmin pull request #2889
Opened 2021-10-08 09:42 UTC by danilo-delbusso

Probably best reviewed at once. Also contains minor style fixes.

Since the two issues addressed here are quite tangled, this PR attempts to fix both:

- Fixes VIF mapping in cross pool migration by reflecting the parameters of the corresponding xapi method
- Adds snapshot VIFs to mapping if they are not present within the ones returned by `VM.VIFs` (e.g.: VIF was deleted before cross pool migration, but after snapshot creation)

2021-10-08 14:28 UTC, CitrixChris requested changes

2021-10-08 14:28 UTC, CitrixChris commented on XenModel/Actions/VM/VMCrossPoolMigrateAction.cs
> +                .Select(Connection.Resolve).SelectMany(snap => snap.VIFs).ToList();
Each operation on a new line as you have done above, keep consistency

2021-10-08 14:28 UTC, CitrixChris commented on XenModel/Actions/VM/VMCrossPoolMigrateAction.cs
> +                if (map.ContainsKey(snapVIF))
I feel with this you can just test the negative and reduce the number of lines here. While using continue would work I don't think its really needed, if we can write less code we maintain less code.

2021-11-01 14:24 UTC, CitrixChris approved these changes

2021-11-08 13:19 UTC, CitrixChris requested changes
Formatting in these files seems to be a little off, just double check the whole files

2021-11-08 13:19 UTC, CitrixChris commented on XenAdmin/Wizards/GenericPages/SelectMultipleVMNetworkPage.cs
> +                        if (row.Cells[1].Value is ToStringWrapper<XenAPI.Network> selectedItem)
formatting is off, more indents please

2021-11-09 11:40 UTC, danilo-delbusso commented on XenAdmin/Wizards/GenericPages/SelectMultipleVMNetworkPage.cs
> +            public string MACAddress { get; set; }
![image](https://user-images.githubusercontent.com/32554698/140917220-bd4a95a7-ef00-493b-b2dd-baaad1af8ee4.png)
Very odd. Seems like GitHub doesn't like it when we mix tabs and spaces, even though in thse commits they're virtually the same.

I will be reverting it

2021-11-09 12:09 UTC, kc284 commented on XenAdmin/Wizards/GenericPages/SelectMultipleVMNetworkPage.cs
> +            public string MACAddress { get; set; }
Stick with spaces. A space is always a space, while tabs are rendered differently by the various interfaces.

2021-11-09 12:20 UTC, danilo-delbusso commented on XenAdmin/Wizards/GenericPages/SelectMultipleVMNetworkPage.cs
> +            public string MACAddress { get; set; }
I'll update the files to only use spaces then, to keep it consistent.

2021-11-15 11:23 UTC, CitrixChris approved these changes

2021-12-14 13:32 UTC, danilo-delbusso commented
Force pushed to rebase onto `master` and resolve conflict in `VmMappings.cs`

2021-12-23 14:12 UTC, kc284 submitted a review, later dismissed
The solution looks ok to me. A couple of remarks:
- The API calls to get snapshots should be replaced by retrieval from the cache.
- I think it is a bit confusing for the user to see the extra VIFs from snapshots against the VM's name. I think it would be clearer if they were shown against the snapshot's name.

I've made the above modifications in this PR https://github.com/danilo-delbusso/xenadmin/pull/13

2021-12-30 17:00 UTC, AaronRobson approved these changes

2022-01-05 09:43 UTC, CitrixChris approved these changes

2022-01-05 11:13 UTC, merged