CA-359712 & CA-359709: Add RBAC check to VM/template copy/clone and Server Status Report Wizard
xenserver/xenadmin pull request #2904
Opened 2021-10-27 13:41 UTC by danilo-delbusso

Also contains a minor refactor of how the RBAC checks are configured, since there was some repeated logic in a few wizards.

2021-11-15 11:10 UTC, CitrixChris requested changes

2021-11-15 12:03 UTC, danilo-delbusso commented on XenAdmin/Wizards/ExportWizard/ExportApplianceWizard.cs
> +                    if (!Helpers.ConnectionRequiresRbac(xenConnection))
Agreed, I'll be moving it back to a separate method

2021-11-18 15:22 UTC, kc284 commented
There are a few issues with this PR, some of which were a result of complicated design of the public interface of clases WzardPermissionCheck and RbacWarningPage. I have submitted the corrections in this PR https://github.com/danilo-delbusso/xenadmin/pull/8. @danilo-delbusso please review and once we correct it and merge it, we'll ask @AaronRobson and @CitrixChris to re-review the total.

2021-11-29 14:50 UTC, CitrixChris approved these changes

2021-12-02 11:53 UTC, AaronRobson approved these changes

2021-12-02 22:27 UTC, kc284 commented
I have submitted https://github.com/danilo-delbusso/xenadmin/pull/12 to resolve the conflicts.

2021-12-03 10:48 UTC, merged