CA-343229: Changing roles when logged in as an AD user only takes effect after logging out/in
xenserver/xenadmin pull request #2905
Opened 2021-11-09 11:28 UTC by danilo-delbusso

Best reviewed commit-by-commit. Whitespace differences are the automatic indent as completed by VS2019.

Took advantage to improve UX slightly:
- Grouped logging out actions into a `MultipleAction` to avoid one RBAc prompt per user disconnection
- Tell user that they're also going to disconnect other users when the selected users include the current one.

Users will still need to insert credentials for two RBAC prompts if they're changing roles to logged in users (one for changing the roles, one for disconnections if necessary). Not ideal but it makes the code tidier since we can reuse methods.

Tested with:

| Changing current user 	| Changing other user(s) 	| Other user(s) are(is) logged in 	| More than one user involved 	| Result 	|
|:---:	|:---:	|---	|---	|---	|
| NO 	| YES 	| NO 	| YES 	| ✅ 	|
| NO 	| YES 	| YES 	| NO 	| ✅ 	|
| NO 	| YES 	| YES 	| YES 	| ✅ 	|
| NO 	| YES 	| NO 	| NO 	| ✅ 	|
| YES 	| NO 	| NO 	| NO 	| ✅ 	|
| YES 	| NO 	| YES 	| NO 	| ✅ 	|
| YES 	| YES 	| YES 	| YES 	| ✅ 	|

2021-11-15 11:18 UTC, CitrixChris requested changes

2021-11-15 11:18 UTC, CitrixChris commented on XenAdmin/TabPages/AdPage.cs
> +                    var suicide = false;
This feels like a negative language thing

2021-11-16 11:10 UTC, AaronRobson approved these changes

2021-11-22 10:00 UTC, CitrixChris approved these changes

2021-12-02 21:29 UTC, kc284 requested changes
Overall I agree with the solution provided, I have a few remarks:
1. The method LoggedInSubjects() in Helpers.cs is making a server call and is called on the UI thread. This practice should be avoided because it causes delays or freezing on the UI.
2. The warning prompts for the case of logging out after a role change need some clarification.
3. If the current logged in user is also logged in from other clients, logging the user out from the current application instance does not log out the other sessions. Note that this is an existing bug and is not caused by the changes in this PR, but we can try fixing it since we're here.

I've made the corrections in this PR https://github.com/danilo-delbusso/xenadmin/pull/11. The majority of changes are because of bullet point 3.

2021-12-16 10:06 UTC, kc284 submitted a review, later dismissed

2021-12-17 10:51 UTC, CitrixChris approved these changes

2021-12-17 11:12 UTC, danilo-delbusso commented
Force push related to trivial merge conflict in `XenModel/Utils/Helpers.cs`

2021-12-17 11:22 UTC, kc284 approved these changes

2021-12-17 11:25 UTC, merged