[CHC] CA-366069 & XSI-1222: Remove case sensitive checks for ISO extension
xenserver/xenadmin pull request #2986
Opened 2022-04-08 13:54 UTC by danilo-delbusso

2022-04-08 14:00 UTC, CitrixChris requested changes

2022-04-08 14:00 UTC, CitrixChris commented on XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs
> +
Random new line at end of file

2022-04-08 14:02 UTC, danilo-delbusso commented on XenAdmin/Wizards/PatchingWizard/PatchingWizard_SelectPatchPage.cs
> +
✔️

2022-04-08 14:18 UTC, CitrixChris approved these changes

2022-04-11 09:19 UTC, AaronRobson approved these changes

2022-04-11 10:07 UTC, kc284 requested changes

2022-04-12 18:48 UTC, kc284 commented on XenModel/Actions/Updates/DownloadAndUnzipXenServerPatchAction.cs
> +                        string currentExtension = Path.GetExtension(iterator.CurrentFileName()).ToLowerInvariant();
The bit `.ToLowerInvariant()` still needs to move from currentExtension in line 203 to currentExtension in line 205.

2022-04-12 18:50 UTC, kc284 commented on XenModel/Actions/Updates/DownloadAndUnzipXenServerPatchAction.cs
> +            skipUnzipping = downloadUpdate && updateFileSuffixes.Any(item => address.ToString().ToLowerInvariant().Contains(item));
The item in the Contains still needs ToLowerInvariant().

2022-04-14 10:36 UTC, kc284 approved these changes

2022-04-14 10:36 UTC, merged