[XC] CA-366069 & XSI-1222: Remove case sensitive checks for ISO extension
xenserver/xenadmin pull request #2987
Opened 2022-04-08 13:55 UTC by danilo-delbusso

2022-04-08 14:00 UTC, CitrixChris approved these changes

2022-04-11 09:16 UTC, AaronRobson commented on XenModel/InvisibleMessages.ja.resx
> +    <value>iso</value>
Nit: It might be worth removing this as a translatable string and having it as a constant in code instead.

2022-04-11 09:18 UTC, AaronRobson commented on XenAdmin/Diagnostics/Hotfixing/SingleHotfix.cs
> +                var filePath = Path.Combine(Program.AssemblyDir, $"{Filename}.{InvisibleMessages.ISO_UPDATE.ToLowerInvariant()}");
I appreciate the use of `...Invariant` functions 👍

2022-04-11 09:18 UTC, AaronRobson submitted a review, later dismissed

2022-04-11 10:08 UTC, kc284 requested changes
Same requests as in PR #2986 (which is why it is a good idea to finish with the one PR first and then port all the changes together in the other branch).

2022-04-12 08:33 UTC, danilo-delbusso commented
> Same requests as in PR #2986 (which is why it is a good idea to finish with the one PR first and then port all the changes together in the other branch).

You're right. I thought this one was fairly straightforward but I was clearly wrong here. 😅

2022-04-12 08:44 UTC, danilo-delbusso commented
Blocking awaiting reviews on the twin PR: #2986

2022-04-19 08:22 UTC, kc284 commented
#2986 has been merged now, you can just cherry pick the commits from that one, squash them and force-push to this PR.

2022-04-19 09:26 UTC, danilo-delbusso commented
> #2986 has been merged now, you can just cherry pick the commits from that one, squash them and force-push to this PR.

Can't quite cherry pick as there's a few differences in `XenModel/Actions/Updates/DownloadAndUnzipXenServerPatchAction.cs`

So double check every change in this PR 🚀

2022-04-19 11:16 UTC, kc284 approved these changes

2022-04-20 08:54 UTC, CitrixChris approved these changes

2022-04-20 08:55 UTC, merged