CA-365905 (XSI-1215): Reworked previous solution:
xenserver/xenadmin pull request #2990
Opened 2022-04-19 10:55 UTC by kc284

Create a temporary file in the target download folder only if the latter is in a different drive from the default temporary folder.

I thought I'd rework this because there are many occasions where the user performs smaller downloads to their local drive and they may find it strange to see a randomly named file in the target folder when it's not strictly necessary since the default temp folder can be used in this case.

2022-04-19 13:18 UTC, danilo-delbusso requested changes

2022-04-19 13:18 UTC, danilo-delbusso commented on XenModel/XenAPI/HTTP.cs
> +            if (Path.GetPathRoot(path) != Path.GetPathRoot(tmpFile))
I'd add a comment to show why we're doing this. Might not be very clear on why we did this in a few years

2022-04-20 08:45 UTC, danilo-delbusso approved these changes

2022-04-22 08:52 UTC, CitrixChris approved these changes

2022-04-22 12:57 UTC, merged