CA-329538: Tell the user to ensure tools are installed if a VM cannot…
xenserver/xenadmin pull request #2997
Opened 2022-04-26 12:37 UTC by kc284

… be migrated via drag-and-drop. Also, show the name of the VM in the various failure messages as drag-and-drop may operate on multiple VMs.

2022-04-27 08:29 UTC, danilo-delbusso requested changes
Since you're making changes to this code, a suggestion (though this could be achieved at another time, in a different PR)

I have noticed that the user can drag a VM to an offline pool, and isn't shown a message. This then results in the Migrate VM wizard being shown.

While this is correct, it'd probably be better if we didn't allow the user to drag the VM to offline host/pools in the first place. 
Is this an easy addition?

![Animation](https://user-images.githubusercontent.com/32554698/165475897-11864f74-4cc4-4893-90a8-4da0343efd48.gif)

2022-04-27 08:29 UTC, danilo-delbusso commented on XenModel/Messages.resx
> +    <value>'{0}' may not migrate at the moment. Have you installed {1} on it?</value>
Not sure I like the wording. Would something on the lines of `Please make sure you have installed {1} on the VM` work better?

2022-04-27 11:46 UTC, kc284 commented
I've updated the message. The drag-drop issue you mentioned above is easy to fix, but I'll send a new PR for it because I discovered one more problem in the same functionality: when the host is live, the UI freezes until the cross-pool migrate wizard is launched.

2022-04-27 12:04 UTC, danilo-delbusso approved these changes

2022-05-09 10:36 UTC, CitrixChris approved these changes

2022-05-09 12:37 UTC, merged