Replaced dismiss button with release notes button. Show the application name in the update button.
xenserver/xenadmin pull request #3005
Opened 2022-05-11 09:37 UTC by kc284

2022-05-11 10:06 UTC, danilo-delbusso requested changes

2022-05-11 10:06 UTC, danilo-delbusso commented on XenModel/InvisibleMessages.resx
> +    <value>http://docs.citrix.com/en-us/citrix-hypervisor/citrix-hypervisor-center/whats-new</value>
this should probably be `https`

2022-05-11 19:27 UTC, danilo-delbusso approved these changes

2022-05-16 12:51 UTC, CitrixChris approved these changes

2022-05-16 13:08 UTC, merged