CP-39818: Auto-launch app after installation is finalized
xenserver/xenadmin pull request #3018
Opened 2022-06-06 11:58 UTC by danilo-delbusso

Example:

https://user-images.githubusercontent.com/32554698/172155939-48d66a4c-2bc8-4384-bd92-73f3e816311d.mp4

The background of the checkbox cannot be changed without worsening UX:

see [issue in GitHub](https://github.com/wixtoolset/issues/issues/1687)
or [thread here](https://wix-users.narkive.com/Ss5GWl5A/checkbox-drawn-with-different-coloured-background)
or [StackOverflow thread](https://stackoverflow.com/questions/31178681/how-can-i-make-the-background-of-an-checkbox-transparent-in-wix)

2022-06-08 07:29 UTC, danilo-delbusso commented
Flagging as ready for review since this is a valid solution, and the checkbox background can be fixed by changing the banner bitmap

2022-06-09 09:32 UTC, kc284 commented on WixInstaller/XenCenter.wxs
> +		<Icon Id="XenCenterICO" SourceFile="$(env.RepoRoot)\Branding\Images\AppIcon.ico" />
Indentation.

2022-06-09 09:33 UTC, kc284 commented on WixInstaller/XenCenter.wxs
> +            <Publish Dialog="ExitDialog"
When the application in already installed and the user wants to repair, the checkbox does not appear. I think we should show it in this case too.

2022-06-09 09:37 UTC, kc284 commented on WixInstaller/XenCenter.wxs
> +            Impersonate="yes" />
I believe we should also add `Return="asyncNoWait"` so the installer won't have to wait until the process starts.

2022-06-09 10:41 UTC, kc284 commented on WixInstaller/XenCenter.wxs
> +        <Property Id="WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT" Value="Launch $(var.BrandProduct)" />
`$(var.BrandConsole)`

2022-06-09 10:58 UTC, kc284 commented on WixInstaller/XenCenter.wxs
> +        <Property Id="WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT" Value="Launch $(var.BrandProduct)" />
In fact this text will need localization.

2022-06-09 11:55 UTC, kc284 commented
Regarding the checkbox background issue, because transparency is at the moment only supported for text controls, a possible workaround might be to use a combination of checkbox without text and a text control to achieve the desired result.

2022-06-09 11:55 UTC, kc284 requested changes
As above.

2022-06-13 13:21 UTC, AaronRobson approved these changes

2022-06-13 15:05 UTC, CitrixChris approved these changes

2022-06-14 13:23 UTC, kc284 approved these changes

2022-06-14 13:24 UTC, merged