CA-359965: Consider `physical_utilisation` value when checking for free space in thinly provisioned SRs
xenserver/xenadmin pull request #3028
Opened 2022-07-19 08:28 UTC by danilo-delbusso

`VdiCreationCanProceed` is only used for this use case and when a new VM is being created. In the latter case, we don't really care about physical utilisation of VMs, since it's only checking template disk sizes.

2022-07-19 13:46 UTC, danilo-delbusso commented
blocked by partial freezing of `master`, this is not going until we unblock the rest

2022-07-20 13:59 UTC, AaronRobson approved these changes

2022-07-25 11:06 UTC, CitrixChris requested changes

2022-07-25 11:06 UTC, CitrixChris commented on XenModel/XenAPI-Extensions/SR.cs
> +            if (isThinlyProvisioned && vdiPhysicalUtilization != null)
above you use one line if statements then here you use brackets, stick to the one line to keep it consistent

2022-07-25 12:54 UTC, CitrixChris approved these changes

2022-09-30 22:31 UTC, kc284 commented
I have added some extra refactoring in https://github.com/xenserver/xenadmin/pull/3028.

2022-10-07 21:53 UTC, kc284 approved these changes

2022-10-10 10:58 UTC, CitrixChris approved these changes

2022-10-10 10:59 UTC, CitrixChris approved these changes

2022-10-11 08:26 UTC, merged