CP-40157: Updates to `GraphDetailsDialog`
xenserver/xenadmin pull request #3091
Opened 2023-02-01 10:53 UTC by danilo-delbusso

- Expose some hidden data sources to UI 
- Update friendly name for xapi_open_fds data source
    - Also apply string sorting
- Add data source description as column in GraphDetailsDialog
- Increase default GraphDetailsDialog width to accomodate new column

Also:

Tidy up source in GraphDetailsDialog
- Rename fields
- Reorder methods
- Rename methods
- Add `sealed` to `DataSourceGridViewRow`

2023-02-02 08:53 UTC, danilo-delbusso commented
Not sure what's happening with the checks:
```log
The content of D:\a\xenadmin\xenadmin\XenModel\FriendlyNames.resx isn't sorted alphabetically.
Please sort it using the script in scripts/sort_strings.ps1:
./sort_strings.ps1 -PATHS D:\a\xenadmin\xenadmin\XenModel\FriendlyNames.resx
```

But I have run the following locally:

```bash
 .\scripts\check_strings_sorting.ps1 -PATHS .\XenModel\FriendlyNames.resx -NOISY -CHECK_LOCALIZED
```
and all three files are shown as sorted.

Similarly, re-applying the sorting results in no changes.

Issue here might be that GitHub is running the action on the PR before the force push? (when there was indeed a sorting issue).

I'd ignore it unless I'm missing something

2023-02-02 09:38 UTC, kc284 requested changes
Maybe move the description column immedaitely after the name as this is how we have it in several other gridviews. Also, because the description may be of unknown and potentially longth length, Isuggest settting its sizing mode to Fill with a minimum width of 100 (i.e. exactly like the name column).

2023-02-02 10:07 UTC, kc284 commented on XenAdmin/Controls/CustomDataGraph/DataSet.cs
> +            Hide = datasourceName == "memory" || datasourceName == "memory_total_kib" || hide;
There is one more place where they need to be shown, see class DataSourceItemList
 in GraphHelper.cs.

2023-02-02 13:54 UTC, kc284 commented
Since you're here, do you think you could add a couple of lines to fix this issue https://github.com/xenserver/xenadmin/issues/3080
The reporter has already suggested the fix, just add
```
case "hits/s":
case "misses/s":
```
under
```
case "requests/s":
case "err/s":
```

2023-02-08 13:46 UTC, kc284 approved these changes

2023-02-13 14:00 UTC, CitrixChris approved these changes

2023-02-13 14:04 UTC, merged