Dead/obsolete code removal and some issues on the AddServerDialog
xenserver/xenadmin pull request #3120
Opened 2023-03-22 16:08 UTC by kc284

My original intention was to just submit commit `Removed obsolete code/hidden functionality...`
After I did it though, for some reason I could not type at all in the AddServerDialog, it kept crashing with overflow symptoms. The problem insisted even when I reset on master and only stopped when I wrote commit `Use the server combobox's item list for autocompletion suggestions`.
While doing this I noticed some issues, which lead to the rest of the commits in this PR.
Please review them separately and if possible see if you have any issues with typing in the AddServerDialog after the changes.

2023-03-23 14:42 UTC, danilo-delbusso requested changes
All good, just one small comment :)

2023-03-23 14:42 UTC, danilo-delbusso commented on XenAdmin/Dialogs/AddServerDialog.resx
nit picky but I will never be able to un-see it:

_"Incorrect username and/or password"_ isn't center-aligned with the ❌ icon anymore
before: 
![image](https://user-images.githubusercontent.com/32554698/227238013-51fe858a-ecd8-49ee-967f-4dad55b20639.png)
after:
![image](https://user-images.githubusercontent.com/32554698/227238153-25477808-3e1d-4584-a144-7cc080752b12.png)

2023-03-23 16:05 UTC, kc284 commented on XenAdmin/Dialogs/AddServerDialog.resx
Hmm, actually it's wrong on either case, the icon should be aligned with the textbox, not the label - at least this is how it is everywhere else in the application. Alternatively the message should be a bit further down and the icon aligned with the Username/Password labels.

2023-03-24 09:00 UTC, danilo-delbusso commented on XenAdmin/Dialogs/AddServerDialog.resx
Great stuff, ty :D 

![image](https://user-images.githubusercontent.com/32554698/227473071-e36e1cf9-bf55-4858-99b2-471b98043cbc.png)

2023-03-24 09:00 UTC, danilo-delbusso approved these changes
<img src='https://emojis.slackmojis.com/emojis/images/1643515474/14957/meow_checkmark.png?1643515474' height='30' />

2023-03-28 13:55 UTC, CitrixChris approved these changes

2023-03-29 21:52 UTC, merged