CA-476480: Prevent two instances from starting after running installer
xenserver/xenadmin pull request #3136
Opened 2023-04-21 10:44 UTC by danilo-delbusso

When an instance of XenCenter is already running, the installer shows the `MsiRMFilesInUse` fragment. Pressing OK within that fragment with the `WixUIRMOption` property set to `UseRM` means that the `RMShutdownAndRestart` event kicks in at the end of the installation.

This happens at the same time as the existing "Launch XenCenter" event (if the matching checkbox is checked), causing in the executable being started twice at about the same time. My guess is that the pipe system is not initialised at that point, and that's how we get two applications.

To avoid this, this commit adds a new custom property: `XS_WixUIRMPressedOk`. This is set to `1` when the user clicks OK on the `WixUIRMOption`. It allows us to know whether or not that dialog was shown at all, as checking `WixUIRMOption` is not possible (it's already set to `UseRM` by default). By checking the value of this property we prevent the "Launch XenCenter" option to be shown if `MsiRMFilesInUse` was shown to the user (and they clicked OK). This applies both in case of a repair and an upgrade from a previous version.

2023-04-24 10:15 UTC, danilo-delbusso commented on WixInstaller/XenCenter.wxs
> +                Value="LaunchApplication">WIXUI_EXITDIALOGOPTIONALCHECKBOX = 1 AND NOT (WixUI_InstallMode="Remove") AND XS_WixUIRMPressedOk="0"
FYI. Technically, if `(WixUI_InstallMode="Remove") AND XS_WixUIRMPressedOk="0"` is `true`, the checkbox won't show at all. This is just an extra check

2023-05-22 23:50 UTC, kc284 commented
As I had written on CA-374325, I still think the page where we specify the installation location is cluttered. The last page has more space - and there are several other installers that have the desktop shortcut option on the last page. Could we give it a go and see how it looks?

2023-06-28 10:08 UTC, danilo-delbusso commented
Reminder to also check installer icon post-uninstall

2023-07-10 12:37 UTC, kc284 commented on WixInstaller/wix_src.patch
> ++                    <Condition Action="show">WIXUI_EXITDIALOGOPTIONALCHECKBOXTEXT AND NOT (WixUI_InstallMode="Remove") AND XS_WixUIRMPressedOk="0"</Condition>
Line 1006 ends in LF instead of CRLF and may cause the patch to fail to apply.

2023-07-10 12:39 UTC, kc284 requested changes
1 line ending needs to change, otherwise it looks ok to me.

2023-07-10 14:07 UTC, kc284 approved these changes

2023-07-10 14:07 UTC, merged