Fixes and enhancements
xenserver/xenadmin pull request #3190
Opened 2023-08-07 15:54 UTC by kc284

2023-08-07 17:03 UTC, danilo-delbusso requested changes
minor change

2023-08-07 17:03 UTC, danilo-delbusso commented on XenAdmin/TabPages/CdnUpdates/CdnExpandableRow.cs
Unrelated to this PR but Synchronize Selected doesn't work on standalone hosts

2023-08-07 17:49 UTC, kc284 commented on XenAdmin/MainWindow.cs
> +                    Updates.CheckForCdnUpdates(coordinator.Connection);
Yes.

2023-08-08 08:39 UTC, danilo-delbusso approved these changes

2023-08-09 12:48 UTC, CitrixChris approved these changes

2023-08-09 12:53 UTC, merged