(master) Removed erroneously added backslashes. Generate the xml files without the BOM.
xenserver/xenadmin pull request #3235
Opened 2023-10-03 09:07 UTC by kc284

This ports to master the corrections committed on release/2023/e via PRs #3231, #3232, #3233.

2023-10-05 08:41 UTC, danilo-delbusso requested changes

2023-10-05 08:41 UTC, danilo-delbusso commented on scripts/xenadmin-build.ps1
> +$bomLessEncoding = New-Object System.Text.UTF8Encoding $false
can we add some context here in the form of a comment? someone simply reading this code won't understand why we're doing this

2023-10-05 09:38 UTC, danilo-delbusso approved these changes
ty for humouring me :) 
<img src='https://emojis.slackmojis.com/emojis/images/1643515474/14957/meow_checkmark.png?1643515474' height='30' />

2023-10-16 13:12 UTC, CitrixChris approved these changes

2023-10-16 21:47 UTC, merged